"""added workspace session to models

Revision ID: 3a8aec5048f2
Revises: 
Create Date: 2026-09-19 14:37:51.164495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8aec5048f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    op.add_column('chunks', sa.Column('repo_name', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('repo_name', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'workspace_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'session_id')
    op.drop_column('documents', 'repo_name')
    op.drop_column('chunks', 'repo_name')
    op.drop_table('workspace_sessions')
    # ### end Alembic commands ###
