"""Added repo name  in doc model

Revision ID: 4f1cccafee30
Revises: bb5f442a4b0a
Create Date: 2026-09-18 16:29:53.366977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1cccafee30'
down_revision: Union[str, Sequence[str], None] = 'bb5f442a4b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('repo_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'repo_name')
    # ### end Alembic commands ###
