"""added embedding field in chunk model

Revision ID: 98e9e7528c9f
Revises: 4f1cccafee30
Create Date: 2026-09-18 19:23:35.343126

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import VECTOR
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e9e7528c9f'
down_revision: Union[str, Sequence[str], None] = '4f1cccafee30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "chunks",
    sa.Column("embedding", VECTOR(), nullable=True)
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
