"""add extracted_path to documents

Revision ID: b015805bd4a9
Revises: 9fca4b28dbb9
Create Date: 2026-09-16 21:17:25.182114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b015805bd4a9'
down_revision: Union[str, Sequence[str], None] = '9fca4b28dbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('extracted_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_path')
    # ### end Alembic commands ###
