"""Added relative path in doc model

Revision ID: bb5f442a4b0a
Revises: 03bdac07732a
Create Date: 2026-09-18 15:12:26.707719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5f442a4b0a'
down_revision: Union[str, Sequence[str], None] = '03bdac07732a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('relative_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'relative_path')
    # ### end Alembic commands ###
