"""create jobs table

Revision ID: d6cc3ec31b3f
Revises: 58a17e953079
Create Date: 2026-09-04 16:13:50.849019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cc3ec31b3f'
down_revision: Union[str, Sequence[str], None] = '58a17e953079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('document_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('jobs_documet_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'documents', ['document_id'], ['id'])
    op.drop_column('jobs', 'documet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('documet_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_documet_id_fkey'), 'jobs', 'documents', ['documet_id'], ['id'])
    op.drop_column('jobs', 'document_id')
    # ### end Alembic commands ###
